var g_defWorld;
function DynamicWorld(){function f(g,a){this.x=g;this.y=a;this.set=function(b,e){this.x=b;this.y=e};this.copy=function(){return new f(this.x,this.y)};this.copyTo=function(b){b.x=this.x;b.y=this.y;return b};this.copyFrom=function(b){this.x=b.x;this.y=b.y;return this};this.add=function(b){return new f(this.x+b.x,this.y+b.y)};this.self_add=function(b){this.x+=b.x;this.y+=b.y;return this};this.mul=function(b){return new f(this.x*b,this.y*b)};this.self_mul=function(b){this.x*=b;this.y*=b;return this};
this.div=function(b){return new f(this.x/b,this.y/b)};this.self_div=function(b){this.x/=b;this.y/=b;return this};this.sub=function(b){return new f(this.x-b.x,this.y-b.y)};this.self_sub=function(b){this.x-=b.x;this.y-=b.y;return this};this.dist=function(b){return Math.sqrt(Math.pow(this.x-b.x,2)+Math.pow(this.y-b.y,2))};this.length=function(){return Math.sqrt(Math.pow(this.x,2)+Math.pow(this.y,2))};this.dot=function(b){return this.x*b.x+this.y*b.y};this.setLength=function(b){var e=this.length();return e==
0?new f(0,0):this.mul(b/e)};this.self_setLength=function(b){var e=this.length();if(e==0){this.y=this.x=0;e=1}return this.self_mul(b/e)};this.normalize=function(){return this.setLength(1)};this.self_normalize=function(){return this.self_setLength(1)};this.rot90=function(){return new f(-this.y,this.x)};this.self_rot90=function(){var b=this.x;this.x=-this.y;this.y=b;return this}}function d(g,a,b,e){this.enabled=true;this.collision=e;this.p1=g;this.p2=a;this.constraint=b;this.constraint.compile(g,a);
this.stabilize=function(h){this.constraint.stabilize(h)};this.run=function(h){return this.enabled=this.constraint.run(h)};this.draw=function(h){this.enabled&&this.constraint.draw(h)};this.getDist=function(){};this.applyForceAt=function(h){this.selectedElement.p1.applyForce(h);this.selectedElement.p2.applyForce(h)}}function c(g,a){this.myWorld=g_defWorld;this.mass=1;this.pos=new f(g,a);this.lastpos=new f(g,a);this.vel=new f(0,0);this.lastvel=new f(0,0);this.oddvel=new f(0,0);var b=new f(0,0);this.vels=
[];this.oddvels=[];this.stabilize=function(){this.oddvel=new f(0,0);for(var e in this.oddvels)this.oddvel.self_add(this.oddvels[e]);this.oddvel.self_mul(1/this.oddvels.length);this.oddvels=[];this.correctCollision("oddvel");this.pos.self_add(this.oddvel);this.oddvel.copyFrom(f.ZERO)};this.run=function(){this.lastvel.copyFrom(this.vel);this.lastpos.copyFrom(this.pos);var e=new f(0,0);for(var h in this.vels)e.self_add(this.vels[h]);e.self_mul(1/this.vels.length);this.vels=[];this.vel.self_mul(g_defWorld.properties.inertia).self_add(e.self_mul(1-
g_defWorld.properties.inertia));b.self_add(g_defWorld.properties.gravity);b.self_mul(1/this.mass/g_defWorld.properties.damping);this.vel.self_add(b);b.copyFrom(f.ZERO);this.correctCollision("vel");this.pos.self_add(this.vel)};this.correctCollision=function(e){if(this.pos.y<0){if(this[e].y<0){if(e==="vel")this.vel.y*=-1;this.pos.y=-0.1}this[e].x/=this.myWorld.properties.friction}else if(this.pos.y>this.myWorld.properties.height){if(this[e].y>0){if(e==="vel")this.vel.y*=-1;this.pos.y=this.myWorld.properties.height+
0.1}this[e].x/=this.myWorld.properties.friction}if(this.pos.x<0){if(this[e].x<0){if(e==="vel")this.vel.x*=-1;this.pos.x=-0.1}this[e].y/=this.myWorld.properties.friction}else if(this.pos.x>this.myWorld.properties.width){if(this[e].x>0){if(e==="vel")this.vel.x*=-1;this.pos.x=this.myWorld.properties.width+0.1}this[e].y/=this.myWorld.properties.friction}};this.draw=function(e){e.save();e.fillStyle="rgb(55,0,0)";e.beginPath();e.arc(this.pos.x,this.pos.y,4,0,Math.PI*2,true);e.fill();e.restore()};this.applyForce=
function(e){b.self_add(e)}}function j(g,a){this.myWorld=g_defWorld;this.mass=1.0E-5;this.pos=new f(g,a);this.lastpos=new f(g,a);this.vel=new f(0,0);this.lastvel=new f(0,0);this.oddvel=new f(0,0);new f(0,0);this.stabilize=function(){};this.run=function(){};this.draw=function(b){b.fillStyle="rgb(5,0,20)";b.beginPath();b.arc(this.pos.x,this.pos.y,6,0,Math.PI*2,true);b.fill()};this.applyForce=function(){}}function i(){this.enabled=true;this.material={heatfac:0.3,heatmax:40,heatdam:20,cooling:0.0010,stressmax:3,
stressdam:20,heatform:0,elasticity:0.5,gummi:0,health:100,weight:0.01};this.damage=this.stress=this.heat=0;this.compile=function(g,a){this.p1=g;this.p2=a;this.dist=g.pos.dist(a.pos)};this.stabilize=function(){var g=this.p2.pos.sub(this.p1.pos).self_mul((this.dist-this.p1.pos.dist(this.p2.pos))*g_defWorld.properties.stabilizeAmount);this.p1 instanceof c&&this.p1.oddvels.push(g.mul(-1));this.p2 instanceof c&&this.p2.oddvels.push(g)};this.run=function(){if(this.damage<=this.material.health){this.stress=
this.dist-this.p1.pos.dist(this.p2.pos);var g=Math.abs(this.p1.pos.dist(this.p2.pos)-this.p1.lastpos.dist(this.p2.lastpos));this.heat+=(g>1?g:0)*0.1;g=Math.abs(this.stress);g_defWorld.globalStressE+=this.stress;g_defWorld.globalStressEAbs+=g;++g_defWorld.numDistConstraints;if(g>g_defWorld.globalStressMax)g_defWorld.globalStressMax=g;g=this.p2.pos.sub(this.p1.pos).self_setLength((this.stress<0?-1:1)*g_defWorld.factor(g));this.p1 instanceof c&&this.p1.vels.push(g.mul(-1));this.p2 instanceof c&&this.p2.vels.push(g);
if(this.stress>=this.material.stressmax)this.damage+=this.material.stressdam*(this.stress-this.material.stressmax);if(this.heat>=this.material.heatmax)this.damage+=this.material.heatdam*(this.heat-this.material.heatmax)*0.01;this.heat*=1-this.material.cooling;return true}else return this.enabled=false};this.draw=function(g){if(this.enabled==true){var a=(this.material.health-this.damage)/this.material.health;if(a<=1.0E-5)a=0;g.lineWidth=1+a*4;g.globalAlpha=a;var b,e;if(this.stress>=this.material.stressmax||
this.heat>=this.material.heatmax){a=0;e=b=255}else{a=Math.floor(Math.pow(this.heat/this.material.heatmax,5)*32)*8;b=Math.floor(Math.abs(this.stress)/this.material.stressmax*32)*8;e=0}g.strokeStyle=r(a+b,b-a,e);g.beginPath();g.moveTo(this.p1.pos.x,this.p1.pos.y);g.lineTo(this.p2.pos.x,this.p2.pos.y);g.stroke()}}}function l(g,a){this.points=g;this.connections=[];this.stabilize=function(e){for(var h in this.connections)this.connections[h].stabilize(e);for(var k in this.points)this.points[k].stabilize(e)};
this.run=function(e){for(var h in this.connections)if(!this.connections[h].run(e)){this.connections[h]==g_defEditor.selectedElement&&g_defEditor.reselect(null);this.connections.splice(h,1)}for(var k in this.points)this.points[k].run(e)};for(var b in a){g=a[b].length>=3?a[b][2]:new i;this.connections.push(new d(this.points[a[b][0]],this.points[a[b][1]],g,a[b].length>3?a[b][3]:false))}this.draw=function(e){for(var h in this.monsters)this.monsters[h].draw(e);for(var k in this.connections)this.connections[k].draw(e);
for(var m in this.points)this.points[m].draw(e)}}this.setDefWorld=function(){g_defWorld=this};this.setDefWorld();this.properties={friction:99,inertia:0.99,damping:1,distmaxforce:1E3,disth1:1.25,disth2:0,distmaximum:3,gravity:new f(0,-0.022),width:1E3,height:550,stabilize:2,stabilizeAmount:0.0075};this.globalStressRecord=this.numDistConstraints=this.globalStressMax=this.globalStressEAbs=this.globalStressE=0;this.objects=[new l([new j(100,1),new j(300,1),new j(100,500),new j(820,550),new c(870,500),
new c(900,500),new c(870,470),new c(580,120),new c(620,100),new c(580,200),new c(620,200),new c(680,200),new c(650,250),new c(620,300),new c(720,330),new c(650,360),new j(100,1),new j(300,1),new c(200,517),new c(300,530),new c(400,540),new c(500,540),new c(600,530),new c(700,530),new c(150,600),new c(250,620),new c(350,630),new c(450,650),new c(550,650),new c(650,630),new c(750,620)],[[0,1],[3,4],[4,5],[5,6],[6,4],[7,8],[8,9],[9,10],[7,10],[7,9],[13,14],[10,11],[8,12],[9,13],[12,10],[12,14],[13,12],
[9,12],[8,11],[12,11],[7,11],[11,14],[13,15],[14,15],[2,18],[18,19],[19,20],[20,21],[21,22],[22,23],[23,3],[2,24],[18,25],[19,26],[20,27],[21,28],[22,29],[23,30],[18,24],[19,25],[20,26],[21,27],[22,28],[23,29],[3,30],[24,25],[25,26],[26,27],[27,28],[28,29],[29,30]])];this.forces=[];this.running=true;this.monsters=[];this.loadObj=function(g){var a=[];for(var b in g.points){var e=g.points[b];switch(e[2]){case "f":a.push(new j(e[0],e[1]));break;case "p":default:a.push(new c(e[0],e[1]))}}b=[];for(var h in g.connections){e=
g.connections[h];var k;k=e.length>=3?e[2]:new i;switch(e[2]){case "d":default:b.push(new d(this.points[connections[e][0]],this.points[connections[e][1]],k))}}return new l(a,b)};DynamicWorld.Vector2D=f;DynamicWorld.Vector2D.ZERO=new f(0,0);DynamicWorld.SimpleConnection=d;DynamicWorld.MassPoint=c;DynamicWorld.FixPoint=j;this.factor=function(g){g=Math.min(Math.abs(g/g_defWorld.properties.distmaximum),1)/1;return(2*Math.pow(g,3)-3*Math.pow(g,2)+1)*0+(-2*Math.pow(g,3)+3*Math.pow(g,2))*g_defWorld.properties.distmaxforce+
(Math.pow(g,3)-2*Math.pow(g,2)+g)*g_defWorld.properties.disth1*g_defWorld.properties.distmaxforce+(Math.pow(g,3)-Math.pow(g,2))*g_defWorld.properties.disth2*g_defWorld.properties.distmaxforce};DynamicWorld.DistConstraint=i;this.run=function(g){this.numDistConstraints=this.globalStressEAbs=this.globalStressE=0;if(this.globalStressRecord<this.globalStressMax)this.globalStressRecord=this.globalStressMax;this.globalStressMax=0;if(this.running){for(var a=0;a<this.properties.stabilize;++a)for(var b in this.objects)this.objects[b].stabilize(g);
for(b in this.objects)this.objects[b].run(g);for(var e in this.monsters)this.monsters[e].run(g);this.forces=[];this.globalStressE/=this.numDistConstraints;this.globalStressEAbs/=this.numDistConstraints}};this.collideVecPointFirst=function(g,a){for(var b in this.objects){var e=this.objects[b].points;for(var h in e)if(e[h].pos.sub(g).length()<a)return{obj:this.objects[b],point:e[h]}}return null};this.collideVecLineFirst=function(g,a){for(var b in this.objects){var e=this.objects[b];for(var h in e.connections){var k=
e.connections[h];if(k.enabled==true){var m=k.p2.pos.sub(k.p1.pos),n=m.normalize(),o=g.sub(k.p1.pos).dot(n);m=m.length();if(o>0&&o<m){n=n.self_mul(o);o=n.add(k.p1.pos);if(o.dist(g)<=a)return{obj:e,con:k,at:o,lerp:n.length()/m}}}}}return null};this.moveVecPhysic=function(g,a,b,e,h){var k=g.add(b),m=Math.min(g.x,k.x)-a,n=Math.max(g.x,k.x)+a,o=Math.min(g.y,k.y)-a;a=Math.max(g.y,k.y)+a;var q,p;for(con in e)if(!(con.p1.pos.x<m&&con.p2.pos.x<m||con.p1.pos.x>n&&con.p2.pos.x>n))if(!(con.p1.pos.y<o&&con.p2.pos.y<
o||con.p1.pos.y>a&&con.p2.pos.y>a)){var s=g.sub(con.p1.pos);k=g.sub(con.p2.pos);s=b.dot(s);k=b.dot(k);if(s<0&&k>0||s>0&&k<0){k=b.mul(s);if(!q||q.sub(g).length()>k.sub(g).length()){q=k;p=con}}}if(q){e=p.p2.pos.sub(p.p1.pos);m=q.sub(p.p1.pos).length()/e.length();p.applyForceAt(g.sub(q).mul(h),m);e.ortho().self_normalize().self_cross(b).self_mul(2).self_add(e)}};this.deleteConnection=function(g){if(g!=null)for(var a=0;a<this.objects.length;a++){var b=this.objects[a].connections,e=b.indexOf(g);if(e!=
-1){b.splice(e,1);g==g_defEditor.selectedElement&&g_defEditor.reselect(null)}}};var r=function(g,a,b){return"rgb("+Math.round(g)+","+Math.round(a)+","+Math.round(b)+")"}};var cuibgcolor="rgb(50,45,40)",cuibgdiscolor="rgb(100,95,90)",cuibgovercolor="rgb(60,55,50)",cuibgpressedcolor=cuibgcolor,cuibgpresseddiscolor=cuibgdiscolor,cuibgpressedovercolor=cuibgovercolor,cuipanelcolor="rgb(35,30,20)",cuifgcolor="rgb(255,255,230)",cuifgdiscolor="rgb(200,200,180)",cuifgpressedcolor="rgb(200,200,180)",cuifgpresseddiscolor="rgb(200,200,180)",cui3dlitcolor="rgb(140,120,100)",cui3ddarkcolor="rgb(10,5,0)",cui3dlitovercolor="rgb(200,180,160)",cui3ddarkovercolor="rgb(10,5,0)";
function cuiBase(f,d){this.children=[];if(this.parent=f){f.children.push(this);this.root=f.root;this.enabled=f.enabled}else this.enabled=true;this.invalidated=true;this.wasMouseover=this.mouseover=false;this.wasEnabled=this.enabled;this.rect=d;this.predraw=function(c){c.save();c.strokeStyle=cui3dlitcolor;c.fillStyle=cuipanelcolor;c.beginPath();c.rect(0,0,this.rect[2],this.rect[3]);c.stroke();c.fill();c.restore()};this.getFgColor=function(c){return this.value&&c?this.enabled?cuifgpressedcolor:cuifgpresseddiscolor:
this.enabled?cuifgcolor:cuifgdiscolor};this.draw3dRect=function(c,j){c.fillStyle=this.enabled?this.value&&j?this.mouseover?cuibgpressedovercolor:cuibgpressedcolor:this.mouseover?cuibgovercolor:cuibgcolor:this.value&&j?this.mouseover?cuibgpressedoverdiscolor:cuibgpresseddiscolor:this.mouseover?cuibgoverdiscolor:cuibgdiscolor;var i=this.mouseover&&this.enabled?cui3dlitovercolor:cui3dlitcolor,l=this.mouseover&&this.enabled?cui3ddarkovercolor:cui3ddarkcolor;if(j&&this.value){j=i;i=l;l=j}c.lineWidth=1.5;
c.beginPath();c.rect(0.5,0.5,this.rect[2]-0.5,this.rect[3]-0.5);c.fill();c.beginPath();c.strokeStyle=i;c.moveTo(0.5,0.5);c.lineTo(this.rect[2]-1.5+1,0.5);c.moveTo(this.rect[2]-0.5,0.5);c.lineTo(this.rect[2]-0.5,this.rect[3]-1.5+1);c.stroke();c.beginPath();c.strokeStyle=l;c.moveTo(this.rect[2]-1.5+1,this.rect[3]-0.5);c.lineTo(0.5,this.rect[3]-0.5);c.moveTo(0.5,this.rect[3]-1.5+1);c.lineTo(0.5,0.5);c.stroke()};this.setEnabled=function(c){this.recursionElem(function(j){j.enabled=c})};this.invalidate=
function(){};this.recursionElem=function(c,j,i){if(this[c])this[c](i);else typeof c=="function"&&c(this,i);for(var l in this.children)this.children[l].recursionElem(c,j,i);if(this[j])this[j](i);else typeof j=="function"&&j(this,i)};this._ismouseover=function(c){if(this.wasEnabled!=this.enabled){this.invalidated=true;this.wasEnabled=this.enabled}if(this.parent&&this.parent.invalidated)this.invalidated=true;if(this.enabled==true){if(this.wasMouseover!=this.mouseover){this.invalidated=true;this.wasMouseover=
this.mouseover}var j=this.getAbsolutePosition();this.mouseRelX=c.x-j[0];this.mouseRelY=c.y-j[1];if(this.mouseRelX>0&&this.mouseRelX<this.rect[2]&&this.mouseRelY>0&&this.mouseRelY<this.rect[3]){this.mouseover=true;if(this.root.clicked)if(this.click){this.invalidated=true;this.click()}}else this.mouseover=false}};this.getAbsolutePosition=function(){for(var c=this,j=this.root.rect[0],i=this.root.rect[1];c!=this.root;){j+=c.rect[0];i+=c.rect[1];c=c.parent}return[j,i]};this._predraw=function(c){c.save();
c.translate(this.rect[0],this.rect[1]);this.predraw&&this.invalidated&&this.predraw(c)};this._postdraw=function(c){this.postdraw&&this.invalidated&&this.postdraw(c);this.invalidated=false;c.restore()};this.deleteMe=function(){var c=this.parent.children.indexOf(this);c!=-1&&this.parent.children.splice(c,1)}}
function cuiRoot(f){this.base=cuiBase;this.base(null,f);var d=this.root=this;this.mousedown=this.clicked=this.mousewasup=this.mousewasdown=false;window.addEventListener("click",function(c){d.click(c)},true);window.addEventListener("mousedown",function(c){d.onmousedown(c)},true);window.addEventListener("mouseup",function(c){d.onmouseup(c)},true);window.addEventListener("mousemove",function(c){d.mousemove(c)},true);this.rundraw=function(c){this.recursionElem("_ismouseover",null,{x:this.mouseX,y:this.mouseY,
click:this.clicked,elem:null});this.clicked=false;this.recursionElem("prerun","postrun");this.recursionElem("_predraw","_postdraw",c)};this.prerun=function(){if(this.mousedown!=this.mousewasdown)if(this.mousedown){this.mousedowntoggle=true;this.mouseuptoggle=false}else{this.mousedowntoggle=false;this.mouseuptoggle=true}else this.mouseuptoggle=this.mousedowntoggle=false;this.mousewasdown=this.mousedown};this.postrun=function(){};this.click=function(){this.clicked=true};this.onmousedown=function(){this.mousedown=
true};this.onmouseup=function(){this.mousedown=false};this.mousemove=function(c){this.mouseX=c.clientX;this.mouseY=c.clientY}}cuiRoot.prototype=new cuiBase;
function cuiButton(f,d,c,j){this.base=cuiBase;this.base(f,d);this.name=c;this.value=false;this.content=j;this.prerun=function(){};this.postrun=function(){};this.predraw=function(i){i.save();this.draw3dRect(i,true);i.textAlign="center";i.fillStyle=this.getFgColor(true);i.globalAlpha=255;if(typeof this.name!="string"){i.textBaseline="top";for(var l in this.name)i.fillText(this.name[l],this.rect[2]/2,l*10,this.rect[2])}else{i.textBaseline="middle";i.fillText(this.name,this.rect[2]/2,this.rect[3]/2,this.rect[2])}i.restore()};
this.postdraw=function(){};this.click=function(){this.invalidated=true;this.value=!this.value;this.onValueChange&&this.onValueChange(!this.value,this.value,this.content)};this.setValue=function(i){if(i!=this.value){var l=this.value;this.value=i;this.onValueChange&&this.onValueChange(l,i,this.content)}};this.getValue=function(){return this.value}}cuiButton.prototype=new cuiBase;
function cuiOptionButtonGroup(f,d,c){this.base=cuiBase;this.base(f,[d[0],d[1],d[2],0]);f=0;for(var j in c){var i=new cuiButton(this,[0,f,d[2],20],c[j][0],c[j][1]);if(j==0){i.value=true;this.activeElem=i}i.click=function(){if(this.parent.activeElem!=this){this.parent.activeElem.value=false;this.parent.activeElem=this;this.value=true;this.parent._onValueChange&&this.parent._onValueChange(this.content)}};f+=i.rect[3]}this.rect[3]=Math.max(d[3],f);this.activeElem=this.children[0];this.prerun=function(){};
this.postrun=function(){};this.predraw=function(){};this.postdraw=function(){};this.getValue=function(){return this.activeElem.content};this.select=function(l){this.activeElem.value=false;this.activeElem=this.children[l];this.activeElem.value=true;this._onValueChange&&this._onValueChange(this.activeElem.content)};this._onValueChange=function(l){this.onValueChange&&this.onValueChange(null,null,l)}}cuiOptionButtonGroup.prototype=new cuiBase;
function cuiSlider(f,d,c,j,i,l,r){this.base=cuiBase;this.base(f,d);this.name=c;this.value=r!=null?r:j;this.min=j;this.max=i;this.margin=3.5;this.doslid=false;var g;this.step=l!=null?l:0.0010;this._setVal=function(a){var b=this.value;this.value=a;this.invalidated=true;this.onValueChange&&this.onValueChange(b,this.value,this.content)};this.setLerp=function(a){g=a;this.updateValueFromLerp()};this.setValue=function(a){g=(this.value-this.min)/(this.max-this.min);this._setVal(a)};this.getValue=function(){return this.value};
this.getLerp=function(){return g};this._updateLerpFromValue=function(){g=(this.value-this.min)/(this.max-this.min)};this._updateLerpFromValue();this.updateValueFromLerp=function(){this._setVal(Math.floor(g*(this.max-this.min)/l)*l+this.min)};this.prerun=function(){if(this.root.mousedowntoggle)this.doslid=this.mouseover;else if(!this.root.mousedown)this.doslid=false;this.doslid&&this.setLerp(Math.min(Math.max(this.mouseRelX-this.margin,0)/(this.rect[2]-2*this.margin),1))};this.postrun=function(){};
this.predraw=function(a){a.save();this.draw3dRect(a);a.beginPath();a.strokeStyle=this.getFgColor();a.moveTo(2.5,this.rect[3]*0.75);a.lineTo(this.rect[2]-2.5,this.rect[3]*0.75);a.stroke();a.beginPath();a.moveTo(this.margin+g*(this.rect[2]-2*this.margin),this.rect[3]*0.6);a.lineTo(this.margin+g*(this.rect[2]-2*this.margin),this.rect[3]-this.margin);a.stroke();a.fillStyle=a.strokeStyle;a.font="bold 11px sans-serif";var b=this.value.toFixed(this.step.toString().length);a.fillText(this.name+": "+b,2,this.rect[3]*
0.45);a.restore()};this.postdraw=function(a){};this.click=function(){}};var g_defEditor;
function DynamicEditor(f,d,c,j){this.setDefEditor=function(){g_defEditor=this};this.scrollOffsetY=this.scrollOffsetX=0;this.height=j;this.width=c;this.viewHeight=j;this.viewWidth=c-200;this.useRaster=true;this.rasterSize=20;this.maxConnectionLen=200;this.invalidated=true;this.setDefEditor();this.canvas=f;this.world=d;this.fastPrototypeMode=true;this.upgrades={strength:{heatfac:1,heatmax:1,heatdam:0.5,cooling:0.5,stressmax:1.5,stressdam:1,heatform:1,elasticity:1,gummi:1,health:1,weight:1},weight:{heatfac:1,
heatmax:1,heatdam:1,cooling:1,stressmax:1,stressdam:1,heatform:1,elasticity:1,gummi:1,health:1,weight:0.5}};this.cui=new cuiRoot([this.viewWidth,0,this.width-this.viewWidth,j]);this.materials=new cuiOptionButtonGroup(this.cui,[90,5,64,10],[["St\u00fctze",{col:false}],["Deck",{col:true}]]);this.materials.onValueChange=function(a){this.selMat=a};this.modes=new cuiOptionButtonGroup(this.cui,[5,5,78,10],[["Editor",{mode:"edit"}],["Physik Test",{mode:"physic"}],["L\u00f6schen",{mode:"delete"}]]);this.saveButton=
new cuiButton(this.cui,[5,116,78,20],"Save building");this.saveButton.click=function(){getOKDialog()};this.getOKDialog=function(){var a=new Node("div");a.style.position="absolute";a.style.display="block";a.style.left="100px";a.style.top="100px";a.style.right="200px";a.style.bottom="200px";document.appendChild(a);return a};this.fastProtoButton=new cuiButton(this.cui,[90,116,78,20],"Klick-Modus");this.fastProtoButton.onValueChange=function(a,b,e){g_defEditor.fastPrototypeMode=b};this.fastProtoButton.setValue(true);
this.pauseButton=new cuiButton(this.cui,[5,80,78,30],"Pause");this.pauseButton.onValueChange=function(a,b,e){d.running=!b;g_defEditor.sendWaveButton.setEnabled(d.running)};this.sendWaveButton=new cuiButton(this.cui,[90,80,78,30],"Wave!");this.sendWaveButton.click=function(){g_defEditor.world.monsters.push(new MovingObject(g_defEditor.world,null))};c=315;(new cuiSlider(this.cui,[5,c+=25,190,25],"Inertia",0.93,0.9999999,1.0E-7,d.properties.inertia)).onValueChange=function(a,b){d.properties.inertia=
b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Dist. Hermite: maxfrce",2E3,0,0.0010,d.properties.distmaxforce)).onValueChange=function(a,b){d.properties.distmaxforce=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Dist. Hermite: h1",5,0,0.0010,d.properties.disth1)).onValueChange=function(a,b){d.properties.disth1=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Dist. Hermite: h2",5,0,0.0010,d.properties.disth2)).onValueChange=function(a,b){d.properties.disth2=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Dist. Hermite: max dist.",
20,1,0.0010,d.properties.distmaximum)).onValueChange=function(a,b){d.properties.distmaximum=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Stabilization-Iterations",10,0,1,d.properties.stabilize)).onValueChange=function(a,b){d.properties.stabilize=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Stabilization-Amount",0.01,0.0010,1.0E-4,d.properties.stabilizeAmount)).onValueChange=function(a,b){d.properties.stabilizeAmount=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Surface-Friction",1,99,1,d.properties.friction)).onValueChange=
function(a,b){d.properties.friction=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"Air-Friction",1,15,1,d.properties.damping)).onValueChange=function(a,b){d.properties.damping=b};(new cuiSlider(this.cui,[5,c+=25,190,25],"GravityY",-0.7,0.7,0.0010,d.properties.gravity.y)).onValueChange=function(a,b){d.properties.gravity.y=b};this.clickOffset=0;this.selectedDialog=null;c=333;var i,l,r,g;this.editingObject=world.objects[0];this.modes.onValueChange=function(a,b,e){g_defEditor.mode=e.mode;switch(e.mode){case "edit":g_defEditor.pauseButton.setEnabled(true);
g_defEditor.materials.setEnabled(true);g_defEditor.fastProtoButton.setEnabled(true);g_defEditor.fastPrototypeMode=g_defEditor.fastProtoButton.value;g_defEditor.mouseManip=false;g_defEditor.mouseEdit=true;g_defEditor.mouseDelete=false;break;case "physic":g_defEditor.pauseButton.setValue(false);g_defEditor.pauseButton.setEnabled(false);g_defEditor.materials.setEnabled(false);g_defEditor.fastProtoButton.setEnabled(false);g_defEditor.fastPrototypeMode=false;g_defEditor.mouseManip=true;g_defEditor.mouseEdit=
false;g_defEditor.mouseDelete=false;break;case "delete":g_defEditor.pauseButton.setEnabled(true);g_defEditor.materials.setEnabled(false);g_defEditor.fastProtoButton.setEnabled(false);g_defEditor.fastPrototypeMode=false;g_defEditor.mouseManip=false;g_defEditor.mouseEdit=false;g_defEditor.mouseDelete=true;break;default:}g_defEditor.updateDialog&&g_defEditor.updateDialog()};this.modes.select(1);this.anim=0;this.mouseDown=false;this.draw=function(a){if(this.invalidated||g_defEditor.world.running){this.invalidated=
false;if(g_defEditor.world.running)this.anim+=0.1;else this.anim=0;a.save();a.translate(-this.scrollOffsetX,-this.scrollOffsetY);a.strokeStyle="rgb(100,100,255)";var b=[[this.mouseOverElement,this.mouseOverType],[this.selectedElement,this.selectedType]];for(var e in b){a.save();var h=b[e];if(h[1]=="Connection"){a.lineWidth=2;a.lineCap="round";a.translate(h[0].p1.pos.x,h[0].p1.pos.y);a.rotate(Math.atan2(h[0].p2.pos.y-h[0].p1.pos.y,h[0].p2.pos.x-h[0].p1.pos.x));a.beginPath();a.moveTo(0,5);h=h[0].p2.pos.sub(h[0].p1.pos).length();
a.lineTo(h,5);a.moveTo(0,-5);a.lineTo(h,-5);a.stroke()}else if(h[1]=="Point"){a.translate(h[0].pos.x,h[0].pos.y);a.lineWidth=2;a.beginPath();a.arc(0,0,6+Math.sin(this.anim)*5,0,Math.PI*2,true);a.stroke()}a.restore();a.strokeStyle="rgb(100,250,100)"}if(this.mouseEdit&&this.mouseDown){a.lineWidth=2;a.lineCap="round";if(this.selectedType=="Point")if(this.mouseOverType=="Connection"){this.invalidated=true;this.predrawConnection(a,this.selectedElement.pos,this.mouseOverElement.p1.pos);this.predrawConnection(a,
this.selectedElement.pos,this.mouseOverElement.p2.pos)}else if(this.mouseOverType=="Point"){this.invalidated=true;this.predrawConnection(a,this.selectedElement.pos,this.mouseOverElement.pos)}else{this.invalidated=true;b=new DynamicWorld.Vector2D(this.cursorX,this.cursorY);if(this.selectedElement.pos.sub(b).length()>this.maxConnectionLen-0.01){b=new DynamicWorld.Vector2D(this.mouseX,this.mouseY);b.self_sub(this.selectedElement.pos).self_setLength(this.maxConnectionLen-0.01);b.x=this.rasterizeOnDemand(b.x+
this.selectedElement.pos.x,-b.x);b.y=this.rasterizeOnDemand(b.y+this.selectedElement.pos.y,-b.y);this.cursorX=b.x;this.cursorY=b.y}this.predrawConnection(a,this.selectedElement.pos,b)}else if(this.selectedType=="Connection")if(this.mouseOverType=="Connection"){this.invalidated=true;this.predrawConnection(a,this.selectedElement.p1.pos,this.mouseOverElement.p1.pos);this.predrawConnection(a,this.selectedElement.p1.pos,this.mouseOverElement.p2.pos);this.predrawConnection(a,this.selectedElement.p2.pos,
this.mouseOverElement.p1.pos);this.predrawConnection(a,this.selectedElement.p2.pos,this.mouseOverElement.p2.pos)}else if(this.mouseOverType=="Point"){this.invalidated=true;this.predrawConnection(a,this.selectedElement.p1.pos,this.mouseOverElement.pos);this.predrawConnection(a,this.selectedElement.p2.pos,this.mouseOverElement.pos)}else{this.invalidated=true;b=new DynamicWorld.Vector2D(this.cursorX,this.cursorY);this.predrawConnection(a,this.selectedElement.p1.pos,b);this.predrawConnection(a,this.selectedElement.p2.pos,
b)}}a.restore();a.save();a.strokeStyle="rgba(200,200,200,10)";a.beginPath();a.globalAlpha=0.6;a.rect(i[0],i[1],i[2],i[3]);a.rect(l[0],l[1],l[2],l[3]);a.rect(r[0],r[1],r[2],r[3]);a.rect(g[0],g[1],g[2],g[3]);a.stroke();a.restore()}};this.validateConnection=function(a,b){return b.sub(a).length()<this.maxConnectionLen};this.predrawConnection=function(a,b,e){a.strokeStyle=this.validateConnection(b,e)?"rgb(90,160,100)":"rgb(255,30,10)";a.beginPath();a.moveTo(b.x,b.y);a.lineTo(e.x,e.y);a.stroke()};this.resize=
function(a,b){this.width=a;this.height=b;this.viewWidth=a-this.cui.rect[2];this.viewHeight=b;this.cui.rect=[this.viewWidth,0,this.cui.rect[2],b];i=[0,this.viewHeight*0.9*0.5,60,this.viewHeight*0.1];l=[this.viewWidth*0.9*0.5,this.viewHeight-60,this.viewWidth*0.1,60];r=[this.viewWidth-60,this.viewHeight*0.9*0.5,60,this.viewHeight*0.1];g=[this.viewWidth*0.9*0.5,0,this.viewWidth*0.1,60]};this.drawUI=function(a){this.cui.rundraw(a)};this.run=function(a){a=new DynamicWorld.Vector2D(g_defEditor.mouseX,g_defEditor.mouseY);
var b=g_defEditor.world.collideVecPointFirst(a,10);g_defEditor.oldMouseOverElement=g_defEditor.mouseOverElement;if(b!=null){g_defEditor.mouseOverElement=b.point;g_defEditor.mouseOverType="Point";g_defEditor.collisionInfo=b}else{b=g_defEditor.world.collideVecLineFirst(a,10);if(b!=null){g_defEditor.mouseOverElement=b.con;g_defEditor.mouseOverType="Connection";g_defEditor.collisionInfo=b}else{g_defEditor.mouseOverElement=null;g_defEditor.mouseOverType="";g_defEditor.collisionInfo=null}}if(g_defEditor.mouseOverElement!=
g_defEditor.oldMouseOverElement)g_defEditor.invalidated=true;if(this.world.running){this.invalidated=true;this.cui.invalidated=true}if(this.mouseDown&&this.mouseManip)if(this.selectedType=="Point")this.selectedElement.applyForce((new DynamicWorld.Vector2D(this.mouseX-this.selectedElement.pos.x,this.mouseY-this.selectedElement.pos.y)).self_mul(0.0040));else if(this.selectedType=="Connection"){a=(new DynamicWorld.Vector2D(this.mouseX-this.selectedElement.p1.pos.x-this.clickOffset.x,this.mouseY-this.selectedElement.p1.pos.y-
this.clickOffset.y)).self_mul(0.0020);this.selectedElement.p1.applyForce(a);this.selectedElement.p2.applyForce(a)}if(this.mouseABSX<this.viewWidth){if(this.mouseABSX<l[0]+l[2]&&this.mouseABSX>l[0]){if(this.scrollOffsetY+this.viewHeight<this.world.properties.height&&this.mouseABSY>this.viewHeight-60){this.scrollOffsetY+=Math.pow(this.mouseABSY-(this.viewHeight-60),2)*0.0020;this.invalidated=true;this.cui.invalidated=true}if(this.scrollOffsetY>0&&this.mouseABSY<60){this.scrollOffsetY-=Math.pow(60-this.mouseABSY,
2)*0.0020;this.invalidated=true;this.cui.invalidated=true}}if(this.mouseABSY<i[1]+i[3]&&this.mouseABSY>i[1]){if(this.scrollOffsetX+this.viewWidth<this.world.properties.width&&this.mouseABSX>this.viewWidth-60){this.scrollOffsetX+=Math.pow(this.mouseABSX-(this.viewWidth-60),2)*0.0020;this.invalidated=true;this.cui.invalidated=true}if(this.scrollOffsetX>0&&this.mouseABSX<60){this.scrollOffsetX-=Math.pow(60-this.mouseABSX,2)*0.0020;this.invalidated=true;this.cui.invalidated=true}}}};this.selectedType=
this.selectedElement=this.mouseOverType=this.mouseOverElement=null;this.reselect=function(a,b){if(a!=this.selectedElement){this.selectedElement=a;this.selectedType=b;this.updateDialog();this.invalidated=true}};this.updateDialog=function(){this.selectedDialog&&this.selectedDialog.deleteMe();if(this.world.running)this.selectedDialog=new this.cuiElementDialog(this.cui,this.selectedElement,this.selectedType)};this.doesConnectionExist=function(a,b){if(a==b)return true;var e=g_defEditor.editingObject.connections;
for(var h in e)if(e[h].p1==a&&e[h].p2==b||e[h].p1==b&&e[h].p2==a)return true;return false};this.createConnection=function(a,b,e){a||alert("no element is selected ");if(!b){if(!g_defEditor.validateConnection(a.pos,new DynamicWorld.Vector2D(g_defEditor.cursorX,g_defEditor.cursorY)))return null;b=new DynamicWorld.MassPoint(g_defEditor.cursorX,g_defEditor.cursorY);e="Point";g_defEditor.editingObject.points.push(b)}g_defEditor.reselect(b,e);if(e=="Point")g_defEditor.validateConnection(a.pos,b.pos)&&!g_defEditor.doesConnectionExist(a,
b)&&g_defEditor.editingObject.connections.push(new DynamicWorld.SimpleConnection(a,b,new DynamicWorld.DistConstraint));else if(e=="Connection"){g_defEditor.validateConnection(a.pos,b.p1.pos)&&!g_defEditor.doesConnectionExist(a,b.p1)&&g_defEditor.editingObject.connections.push(new DynamicWorld.SimpleConnection(a,b.p1,new DynamicWorld.DistConstraint));g_defEditor.validateConnection(a.pos,b.p2.pos)&&!g_defEditor.doesConnectionExist(a,b.p2)&&g_defEditor.editingObject.connections.push(new DynamicWorld.SimpleConnection(a,
b.p2,new DynamicWorld.DistConstraint))}return b};this.cursorY=this.cursorX=this.mouseY=this.mouseX=0;this.mousedown=function(a){if(a.target==f&&g_defEditor.mouseABSX<g_defEditor.viewWidth){g_defEditor.mouseDown=true;if(g_defEditor.mouseOverElement||!g_defEditor.fastPrototypeMode)g_defEditor.reselect(g_defEditor.mouseOverElement,g_defEditor.mouseOverType);if(g_defEditor.collisionInfo&&g_defEditor.selectedType=="Connection"){g_defEditor.collisionLerp=g_defEditor.collisionInfo.lerp;g_defEditor.clickOffset=
g_defEditor.collisionInfo.at.sub(new DynamicWorld.Vector2D(g_defEditor.selectedElement.p1.pos.x,g_defEditor.selectedElement.p1.pos.y))}else g_defEditor.clickOffset=0}};this.mouseup=function(a){if(g_defEditor.mouseDown){g_defEditor.mouseDown=false;if(a.target==f&&g_defEditor.mouseABSX<g_defEditor.viewWidth){if(g_defEditor.mouseEdit)if(g_defEditor.selectedType=="Point")g_defEditor.createConnection(g_defEditor.selectedElement,g_defEditor.mouseOverElement,g_defEditor.mouseOverType);else if(g_defEditor.selectedType==
"Connection"){a=g_defEditor.selectedElement;var b=g_defEditor.createConnection(a.p1,g_defEditor.mouseOverElement,g_defEditor.mouseOverType);g_defEditor.createConnection(a.p2,b==null?g_defEditor.mouseOverElement:b,g_defEditor.mouseOverType==""?"Point":g_defEditor.mouseOverType)}g_defEditor.mouseDelete&&g_defEditor.mouseOverType=="Connection"&&g_defEditor.world.deleteConnection(g_defEditor.mouseOverElement)}}};this.mousemove=function(a){g_defEditor.mouseX=a.clientX+g_defEditor.scrollOffsetX;g_defEditor.mouseY=
-a.clientY+g_defEditor.viewHeight+g_defEditor.scrollOffsetY;g_defEditor.cursorX=g_defEditor.rasterizeOnDemand(g_defEditor.mouseX);g_defEditor.cursorY=g_defEditor.rasterizeOnDemand(g_defEditor.mouseY);g_defEditor.mouseABSX=a.clientX;g_defEditor.mouseABSY=-a.clientY+g_defEditor.height};this.rasterizeOnDemand=function(a,b){return g_defEditor.useRaster&&!g_defEditor.world.running&&g_defEditor.mouseEdit?b==null||b==0?Math.round(a/g_defEditor.rasterSize)*g_defEditor.rasterSize:b<0?Math.floor(a/g_defEditor.rasterSize)*
g_defEditor.rasterSize:Math.ceil(a/g_defEditor.rasterSize)*g_defEditor.rasterSize:a};window.addEventListener("mousedown",this.mousedown,true);window.addEventListener("mouseup",this.mouseup,true);window.addEventListener("mousemove",this.mousemove,true);g_defEditor.isElemAnimated=[];this.cuiElementDialog=function(a,b,e){this.base=cuiBase;this.base(a,[0,145,g_defEditor.cui.rect[2],185]);this.startLerp=function(n,o,q,p,s){var v=[],w,u=0,y=50/q;for(var x in n)v[x]=o[x];w=setInterval(function(){for(var t in n)o[t]=
v[t]+(n[t]-v[t])*((-Math.cos(u*Math.PI)+1)/2);u+=y;p&&p(u);if(u>=1){for(t in n)o[t]=n[t];clearInterval(w);s&&s()}},50)};this.elem=b;this.type=e;this.paper={};if(e=="Connection"){a=5;var h=25,k=new cuiSlider(this,[5,a,165,h],"Length",this.elem.constraint.dist-100>0?this.elem.constraint.dist-100:15,this.elem.constraint.dist+100,0.1,this.elem.constraint.dist),m=this;k.onValueChange=function(n,o){m.paper.dist=o};e=new cuiButton(this,[5,a+=h+5,64,h],"Submit");h=new cuiButton(this,[106,a,64,h],"Animate");
e.onValueChange=function(n,o,q){m.setEnabled(false);if(o){k.initLerp=k.getLerp();g_defEditor.isElemAnimated[m.elem]=true;n=[];for(var p in m.paper)n[p]=m.paper[p];m.startLerp(n,m.elem.constraint,3E3,function(s){k.setLerp(k.initLerp+(0.5-k.initLerp)*((-Math.cos(s*Math.PI)+1)/2))},function(){g_defEditor.isElemAnimated[m.elem]=false;g_defEditor.updateDialog()})}};if(!b.upgrades)b.upgrades={strength:0,weight:0,damage:0};h=45;(new cuiButton(this,[5,a+=h+5,80,h],["Strength:",""+b.constraint.material.stressmax+
"(=>"+b.constraint.material.stressmax*g_defEditor.upgrades.strength.stressmax+")","900$","Upgrade"])).click=function(n,o,q){for(var p in g_defEditor.upgrades.strength)m.elem.constraint.material[p]*=g_defEditor.upgrades.strength[p];this.name[1]=""+m.elem.constraint.material.stressmax+"(=>"+m.elem.constraint.material.stressmax*g_defEditor.upgrades.strength.stressmax+")";++m.elem.upgrades.strength;this.value=false};(new cuiButton(this,[90,a,80,h],["Weight:",""+b.constraint.material.weight+" (=>"+b.constraint.material.weight*
g_defEditor.upgrades.strength.weight+")","900$","Upgrade"])).click=function(n,o,q){for(var p in g_defEditor.upgrades.weight)m.elem.constraint.material[p]*=g_defEditor.upgrades.weight[p];this.name[1]=""+m.elem.constraint.material.weight+" (=>"+m.elem.constraint.material.weight*g_defEditor.upgrades.weight.weight+")";++m.elem.upgrades.weight};e=new cuiButton(this,[5,a+=h+5,165,h],["Health:",""+(b.constraint.material.health-b.constraint.damage)+"(/100)","100$","Repair"]);e.click=function(n,o,q){m.elem.constraint.damage=
0};e.prerun=function(){this.name[1]=""+(b.constraint.material.health-b.constraint.damage)+"(/100)"}}this.setEnabled(g_defEditor.isElemAnimated[b]!=true)}};function drawBots(f,d){f.save();f.fillStyle="rgb(0,0,0)";f.strokeStyle="black";f.lineWidth=2;f.lineCap="round";for(var c in d.objects)d.objects[c].draw(f);f.restore()};var toolbarwidth=200,mousex=500,mousey=500,width=0,height=0,world=new DynamicWorld;world.properties.width=2E3;world.properties.height=2E3;var editor,initTime=(new Date).getTime(),globalAnim=0,intro=[["...",20,70],[".",17,50],["..",50,100]],offsetTime=0,introIndex=0,drawCurve=true;
function init(){window.onresize=resize;window.addEventListener("mousemove",mousemove,true);var f=document.getElementById("canvas");editor=new DynamicEditor(f,world,width,height);if(f.getContext){resize();run();setInterval("run()",1)}else{f=document.createElement("p");f.innerHTML='\t<font face="Arial">\n\t\t\t\t\t\t\t\t\t<b>Dein alter Browser wird nicht unterst&uuml;tzt. W&auml;hle doch einen neuen:\n\t\t\t\t\t\t\t\t\t</b>\n\t\t\t\t\t\t\t\t\t<center>\n\t\t\t\t\t\t\t\t\t\t<a style="border: none;" href="http://windows.microsoft.com/ie9"><img src="Internet_Explorer_9_Icon_by_Misaki2009.png" alt="Icon by Misaki2009" /></a>\n\t\t\t\t\t\t\t\t\t\t<a style="border: none;" href="http://www.google.com/chrome"><img src="chrome.jpg" /></a>\n\t\t\t\t\t\t\t\t\t\t<a style="border: none;" href="http://www.mozilla.com/de/firefox/"><img src="firefox-128.png" /></a>\n\t\t\t\t\t\t\t\t\t</center>\n\t\t\t\t\t\t\t\t</font>';
document.body.replaceChild(f,document.getElementById("canvas"))}editor.cui.postdraw=function(){drawCurve=true}}var lastTime=(new Date).getTime();
function run(){var f=document.getElementById("canvas"),d=f.getContext("2d");d.fillStyle="rgb(200,255,200)";world.run(1);world.run(1);editor.run(1);var c=(new Date).getTime(),j=c-lastTime;lastTime=c;if(world.running||editor.invalidated){f.width=f.width;d.save();d.setTransform(1,0,0,-1,0,height);d.save();d.translate(-editor.scrollOffsetX,-editor.scrollOffsetY);drawBots(d,world);d.restore();editor.cui.invalidated|=editor.invalidated;editor.draw(d);d.restore();d.save();d.translate(this.width/2,this.height-
5);d.fillStyle="rgb(0,0,0)";d.font="bold 12px sans-serif";d.fillText("Daniel Bulla, v0.6, 1st Mar. 11",0,0);d.fillText("fps: "+Math.floor(1E3/j),-70,0);d.restore()}drawCurve|=world.running||editor.invalidated||editor.cui.invalidated;editor.drawUI(d);if(drawCurve){drawCurve=false;f=width-toolbarwidth+5;d.strokeStyle="rgb(55,0,0)";d.fillStyle="rgb(235,245,255)";d.beginPath();d.rect(f-3,637,196,106);d.fill();d.beginPath();d.moveTo(f,640);d.lineTo(f,740);d.lineTo(f+190,740);d.moveTo(f,740-world.factor(0)*
0.05);for(c=0;c<=100;++c){var i=c/100*6;d.lineTo(f+c/100*190,740-world.factor(i)*0.05)}d.fillText("6px",f+190-11,758);d.moveTo(f+190,735-world.factor(i)*0.05);d.lineTo(f+190,750);d.stroke();d.strokeStyle=d.fillStyle="rgb(255,0,0)";d.beginPath();d.moveTo(f+world.globalStressMax/6*190,640);d.lineTo(f+world.globalStressMax/6*190,740);d.fillText("curr max",f,750);d.stroke();d.strokeStyle=d.fillStyle="rgb(0,255,255)";d.beginPath();d.moveTo(f+world.globalStressE/6*190,640);d.lineTo(f+world.globalStressE/
6*190,740);d.fillText("avg",f,760);d.stroke();d.strokeStyle=d.fillStyle="rgb(255,255,0)";d.beginPath();d.moveTo(f+world.globalStressEAbs/6*190,640);d.lineTo(f+world.globalStressEAbs/6*190,740);d.fillText("avg abs",f,770);d.stroke();d.strokeStyle=d.fillStyle="rgb(128,0,0)";d.beginPath();d.moveTo(f+world.globalStressRecord/6*190,740-world.factor(world.globalStressRecord)*0.05);d.lineTo(f+world.globalStressRecord/6*190,740);d.fillText("max",f,780);d.stroke()}d.save();d.translate(width-toolbarwidth,10);
d.lineWidth=2;d.beginPath();d.arc(0,0,6+Math.sin(globalAnim)*5,0,Math.PI*2,true);d.stroke();d.restore();drawIntro(d);globalAnim=((new Date).getTime()-initTime)*0.01}
function drawIntro(f){if(introIndex<intro.length)if(globalAnim<intro[introIndex][2]+offsetTime){editor.invalidated=true;f.save();f.translate((width-toolbarwidth)/2-20,height/2+50-(globalAnim-offsetTime));f.rotate((globalAnim-offsetTime)*0.01-45/intro[introIndex][2]);f.textAlign="center";f.textBaseline="middle";f.font="bold "+intro[introIndex][1]+"px sans-serif";var d=(-Math.cos(Math.pow(globalAnim-offsetTime,2)/Math.pow(intro[introIndex][2],2)*2*Math.PI)+1)*0.5;d=d>1.0E-5?""+d+")":"0.0)";f.fillStyle=
"rgba(180,200,128,"+d;f.fillText(intro[introIndex][0],20,-50);f.strokeStyle="rgba(0,0,0,"+d;f.strokeText(intro[introIndex][0],20,-50);f.restore()}else{offsetTime+=intro[introIndex][2];++introIndex}}function mousemove(f){mousex=f.clientX;mousey=f.clientY}
function resize(){var f=document.getElementById("canvas");if(navigator.appName.indexOf("Microsoft")!=-1){width=window.innerWidth-2;height=window.innerHeight-6}else if(window.innerWidth){width=window.innerWidth-2;height=window.innerHeight-2}else if(document.body&&document.body.offsetWidth){width=document.body.offsetWidth-2;height=document.body.offsetHeight-2}editor.resize(width,height);f.setAttribute("width",width);f.setAttribute("height",height)};
